language: node_js

dist: xenial

services:
  - xvfb

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  yarn: true
  directories:
    - ~/.cache/Cypress

node_js: 13.9

before_install:
  - npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
  - export DISPLAY=:99.0

before_script:
- DEBUG=eslint:cli-engine yarn lint:all
- yarn build

deploy:
- provider: script
  script: yarn publish:release ${TRAVIS_TAG} --yes
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_TAG != "" && $TRAVIS_TAG != *"-"*
    repo: ringcentral/web-apps
- provider: script
  script: yarn publish:release ${TRAVIS_TAG} --yes --dist-tag next
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_TAG == *"-"*
    repo: ringcentral/web-apps